### ISSUE TITLE
I use your default example and get this error

### ISSUE THREAD

**Issue by NickCashFlow** [iliiliiliili/easy-telegram-mtproto#2]
Hi, I use your default example and get this error 

```
config errors
{
  keyword: 'type',
  dataPath: '.api.api_id',
  schemaPath: '#/properties/api/properties/api_id/type',
  params: { type: 'number' },
  message: 'should be number'
}
(node:9888) UnhandledPromiseRejectionWarning: Error: wrong config fields
    at configValidator (D:\projects\tg-zero-cheker\node_modules\telegram-mtproto
\lib\service\main\config-validation.js:112:11)
    at configNormalization (D:\projects\tg-zero-cheker\node_modules\telegram-mtp
roto\lib\service\main\index.js:91:34)
    at new MTProto (D:\projects\tg-zero-cheker\node_modules\telegram-mtproto\lib
\service\main\index.js:60:19)
    at MTProto (D:\projects\tg-zero-cheker\node_modules\telegram-mtproto\lib\ser
vice\main\wrap.js:14:17)
    at init (D:\projects\tg-zero-cheker\node_modules\easy-telegram-mtproto\teleg
ram-mtproto.js:26:12)
    at new TelegramClient (D:\projects\tg-zero-cheker\node_modules\easy-telegram
-mtproto\telegram-client.js:73:32)
    at main (D:\projects\tg-zero-cheker\new\index.js:8:20)
    at Object.<anonymous> (D:\projects\tg-zero-cheker\new\index.js:40:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
(node:9888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:9888) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

```

That's my code default example
```
const TelegramClient = require ('easy-telegram-mtproto');
const data = require ('./login-data.json');

const main = async () => {

    console.log (data);

    const client = new TelegramClient (data.app.api_id, data.app.api_hash,
        data.phone,
        async () => data.phone,
        () => {

            const readline = require ('readline');

            const rl = readline.createInterface ({
                input: process.stdin,
                output: process.stdout
            });

            return new Promise (resolve => {

                rl.question ('Code', (answer) => {

                    rl.close ();
                    resolve (answer);
                });
            });
        });

    await client.login ();

    const chats = await client.getChats ();
    const me = chats.find ((chat) => chat.self);

    console.log (me);

    client.sendMessage (me, 'Hello, is it me you\'re looking for?');
};

main ();
```

node version 12.10.0

What I do wrong?

**Comment by NickCashFlow** [comment]
My wrong, a didn't know that config file `login-data.json` should look like this
```
{
  "phone": "YOU_PHONE_NUMBER",
  "app": {
    "api_id": YOU_API_ID, //should be number
    "api_hash": "YOU_API_HASH"
  }
}
```
But after looking at the code, this file must be duplicated in the working directory and the module folder, and this violates the architectural pattern "single source of truth"

**Comment by iliiliiliili** [comment]
Hi, thank you for your interest.

login-data.json is used only in example code and is not required by the library to exist: you can pass arguments to the TelegramClient constructor in any way you want to.
So you can keep only one file with data in any location and just pass it to the constructor.
